spring:
  datasource:
    url: jdbc:mariadb:/localhost:60001/db23101
    driver-class-name: org.mariadb.jdbc.Driver
    username: dbid231
    password: dbpass231

ssh:
  remote_jump_host: 210.102.178.98
  ssh_port: 60001
  user: t23101
  private_key: Ce36046!
  database_port: 60001

jwt:
  secret:
    key: ThWmZq4t7w!z%C*F-
