spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test1
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qkqh7894563!2
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M