spring:
  datasource:
    #url: jdbc:mariadb://localhost:3306/test1
    #driver-class-name: org.mariadb.jdbc.Driver
    #username: root
    #password: qkqh7894563!2
    url: jdbc:mariadb://localhost:[forwardedPort]/db23101
    driver-class-name: org.mariadb.jdbc.Driver
    username: dbid231
    password: dbpass231
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
      
ssh:
  remote_jump_host: ceprj.gachon.ac.kr
  ssh_port: 60001
  user: t23101
  private_key: ~/.ssh/id_rsa
  database_port: 60001
  
jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M
