spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbid231
    password: dbpass231
    url: jdbc:mysql://ceprj.gachon.ac.kr:60001/db23101

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create

jwt:
  secret:
    key: ThWmZq4t7w!z%C*F-JaNcRfUjXn2r5u8